apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes
spec:
  replicas: 5
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      labels:
        app: login
    spec:
      containers:
      - name: login
        image: coderhouse69990/login:latest  
        ports:
        - containerPort: 8080
        env:   
        - name: MONGO_URL
          value: "mongodb+srv://coderhouse69990:coderhouse@cluster0.k8gmho6.mongodb.net/Kubernetes?retryWrites=true&w=majority&appName=Cluster0"
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
spec:
  selector:
    app: login
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
